In [2]:
import numpy as np

In [19]:
np.array([[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]],dtype=int)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [4]:
np.ones((4,3,5),dtype=np.int16)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int16)

In [13]:
np.arange(0,2,9)

array([0])

In [12]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [14]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [24]:
np.random.random((2,2,2))

array([[[0.49180192, 0.34581107],
        [0.11463519, 0.9861671 ]],

       [[0.38863675, 0.95910659],
        [0.53760791, 0.02766979]]])

In [30]:
np.empty((2,2))

array([[0.89105992, 0.67303557],
       [0.29622432, 0.24546497]])

In [43]:
np.save("my_file",np.random.random((2,5,3)))

In [45]:
np.load('my_file.npy')

array([[[0.40659191, 0.98457817, 0.96277168],
        [0.24873233, 0.9526983 , 0.21119794],
        [0.11033063, 0.74151476, 0.35393293],
        [0.88019254, 0.07860204, 0.92112684],
        [0.75815076, 0.10224377, 0.60879499]],

       [[0.96433793, 0.08442785, 0.57492269],
        [0.81632312, 0.98797928, 0.43168378],
        [0.24776267, 0.50651386, 0.53643187],
        [0.92792005, 0.68554673, 0.77744025],
        [0.59477612, 0.13840127, 0.15041519]]])

In [80]:
x=np.random.random((5,4))

In [89]:
x=np.linspace(1,2,9)
print(x)
x.astype(int)

[1.    1.125 1.25  1.375 1.5   1.625 1.75  1.875 2.   ]


array([1, 1, 1, 1, 1, 1, 1, 1, 2])

In [94]:
np.info(np.ndim)

 ndim(*args, **kwargs)

Return the number of dimensions of an array.

Parameters
----------
a : array_like
    Input array.  If it is not already an ndarray, a conversion is
    attempted.

Returns
-------
number_of_dimensions : int
    The number of dimensions in `a`.  Scalars are zero-dimensional.

See Also
--------
ndarray.ndim : equivalent method
shape : dimensions of array
ndarray.shape : dimensions of array

Examples
--------
>>> np.ndim([[1,2,3],[4,5,6]])
2
>>> np.ndim(np.array([[1,2,3],[4,5,6]]))
2
>>> np.ndim(1)
0


In [104]:
y=np.arange(10,45,4)

In [115]:
print(x.shape,y.shape)
np.array_equal(x,y)

(9,) (9,)


False

In [198]:
z=np.array([np.arange(1,10,1),np.linspace(1,99,9),np.arange(91,100,1)],dtype=int)
print(z[[1,2,0,1]],end="\n\n")
print(z[[1,2,0,1]] [:,[1,0,0,2,5,3,4]])


[[ 1 13 25 37 50 62 74 86 99]
 [91 92 93 94 95 96 97 98 99]
 [ 1  2  3  4  5  6  7  8  9]
 [ 1 13 25 37 50 62 74 86 99]]

[[13  1  1 25 62 37 50]
 [92 91 91 93 96 94 95]
 [ 2  1  1  3  6  4  5]
 [13  1  1 25 62 37 50]]


In [202]:
z.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9,  1, 13, 25, 37, 50, 62, 74, 86,
       99, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [205]:
z.reshape(9,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 1, 13, 25],
       [37, 50, 62],
       [74, 86, 99],
       [91, 92, 93],
       [94, 95, 96],
       [97, 98, 99]])

In [221]:
print(z.shape,x.shape)
np.concatenate((x,np.array([1,2,6,4,5,7,9,3,5])))

(3, 9) (9,)


array([1.   , 1.125, 1.25 , 1.375, 1.5  , 1.625, 1.75 , 1.875, 2.   ,
       1.   , 2.   , 6.   , 4.   , 5.   , 7.   , 9.   , 3.   , 5.   ])

In [226]:
print(z,x.reshape(9,1),z.shape,x.shape)

[[ 1  2  3  4  5  6  7  8  9]
 [ 1 13 25 37 50 62 74 86 99]
 [91 92 93 94 95 96 97 98 99]] [[1.   ]
 [1.125]
 [1.25 ]
 [1.375]
 [1.5  ]
 [1.625]
 [1.75 ]
 [1.875]
 [2.   ]] (3, 9) (9,)


In [235]:
np.vsplit(z,3)

[array([[1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[ 1, 13, 25, 37, 50, 62, 74, 86, 99]]),
 array([[91, 92, 93, 94, 95, 96, 97, 98, 99]])]

In [236]:
list_1 = [1, 2 , 3]
list_2 = [4, 5, 6]
list_3 = [7, 8, 9]
np.array([list_1,list_2,list_3])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [245]:
list_1 = [2,3,4,5]
list_2 = [7,8,9,6]
l1,l2=np.array([list_1]),np.array([list_2])
(l1*l2).tolist()[0]

[14, 24, 36, 30]

In [250]:
x,m,n=int(input()),int(input()),int(input())
np.full((m,n),x)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [252]:
np.arange(5,51,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [259]:
list_1 = [10,11,12,13]
list_2 = [15,12,13,14]
x=np.array([list_1,list_2])
print(np.shape(x),np.ndim(x))

(2, 4) 2


In [261]:
array_1 = np.array([1,2,3,5,4,6,7,8,5,3,2])
print(array_1[:3])#slice of 0 to 2
print(array_1[0::2])#jump of 2 from 0 index

[1 2 3]
[1 3 4 7 5 2]


In [269]:
np.array([(1,2,3),(4,5,6),(7,8,9)])[:,1]

array([2, 5, 8])

In [277]:
x=np.array([(11,12,13,14),(21,22,23,24),(31,32,33,34)])
print(x[:,0],x[0],x[:,-1],x[-1])

[11 21 31] [11 12 13 14] [14 24 34] [31 32 33 34]


In [285]:
array_3 = np.array([1,2,3,5,4,6,7,8,5,3,2])
x=np.vectorize(np.divide)
x(array_3,5)

array([0.2, 0.4, 0.6, 1. , 0.8, 1.2, 1.4, 1.6, 1. , 0.6, 0.4])

In [295]:
array_1 = np.array([(1,2,3,0),(5,4,6,4),(9,7,8,5),(1,3,2,7)])
print(np.linalg.inv(array_1),np.linalg.eigvals(array_1),np.linalg.eig(array_1)[1],np.linalg.det(array_1),sep="\n\n")

[[-0.4         0.06666667  0.13333333 -0.13333333]
 [ 0.52       -0.85333333  0.39333333  0.20666667]
 [ 0.12        0.54666667 -0.30666667 -0.09333333]
 [-0.2         0.2        -0.1         0.1       ]]

[17.26732416  5.44651327 -1.85318104 -0.8606564 ]

[[ 0.20494621  0.29610733 -0.65122105  0.0073581 ]
 [ 0.51981704  0.11206506 -0.17685272 -0.82137942]
 [ 0.76476412  0.36417168  0.73725233  0.54302265]
 [ 0.32081636 -0.87586578 -0.03306444  0.17437919]]

150.00000000000009


In [1]:
#pandas practise from here
import pandas as pd

In [13]:
df=pd.read_csv('KnowYourCohort.csv')

In [15]:
df['Years Of Exp']=df['Years Of Exp'].apply(lambda x:x.split('+')[0]).astype(float)
round(df['Years Of Exp'].mean())

7

In [19]:
len(df[df['Years Of Exp']>10])

3

In [21]:
df.Gender=df.Gender.apply(lambda x:x.lower())

In [27]:
100*df.Gender.value_counts(normalize=True)

male      90.05848
female     9.94152
Name: Gender, dtype: float64

In [30]:
df.City=df.City.apply(lambda x:x.lower())
df.City=df.City.apply(lambda x:x.split(',')[0])
df.City=df.City.apply(lambda x:x.split(' ')[0])

In [46]:
df.City=df.City.replace(['bangalore','banglore','bangalore'],'bengaluru')

In [48]:
100*df.City.value_counts(normalize=True)

bengaluru     56.140351
pune           8.771930
hyderabad      5.847953
kolkata        4.093567
mumbai         2.923977
chennai        2.923977
delhi          2.339181
gurgaon        1.754386
new            1.754386
ghaziabad      1.169591
noida          1.169591
faridabad      1.169591
cary           0.584795
nantong        0.584795
durban         0.584795
gurugram       0.584795
chandigarh     0.584795
mysuru         0.584795
melbourne      0.584795
dubai          0.584795
jaipur         0.584795
houston        0.584795
pittsburgh     0.584795
ahmedabad      0.584795
charlotte      0.584795
jamshedpur     0.584795
ludhiana       0.584795
vijayawada     0.584795
mangalore      0.584795
Name: City, dtype: float64

In [49]:
df.City.value_counts().index[1]

'pune'